AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CurrentRegion:
    Type: String
    Default: us-east-2
  DlFmwrkPrefix:
    Type: String
    Default: dl-fmwrk
  AwsAccount:
    Type: String
    Default: "315119964270"
  srcSysId:
    Type: Number
    Default: 99999999

Resources:
  SourceSystemS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      BucketName: !Join ["", [!Ref DlFmwrkPrefix, "-", !Ref srcSysId, "-", !Ref CurrentRegion]]